apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv-log
spec:
  accessModes:
    - ReadWriteMany # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /pv/log