apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  
