apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  resources:
    requests:
      storage: 1Gi