apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs_share/registry
    server: 192.168.111.136
