apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-1
spec:
  containers:
  - name: simple-webapp-1
    image: kodekloud/webapp-delayed-start
    livenessProbe: # Checkes If app has crashed
        httpGet:
         path: /live
         port: 8080
        initialDelaySeconds: 80 # This is important for livelyness pod. If this this is too lower kubernetes will think app already crashed and will keep restarting the app
        periodSeconds: 1