apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-deployment
  labels:
    app: mysql

spec:
  serviceName: mysql-h
  template:
    # Pod definition
    metadata:
      name: myapp-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql

  replicas: 3