apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
    - name: simple-webapp-color
      image: simple-webapp-color
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"] # Capabilities are supported only at container level and NOT POD level
      envFrom:
        - secretRef:
            name: app-secret
            