apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-1
spec:
  containers:
  - name: simple-webapp-1
    image: kodekloud/webapp-delayed-start
    readinessProbe: # Check if app is ready to serve traffic
        httpGet:
         path: /live
         port: 8080
        initialDelaySeconds: 50
        periodSeconds: 5
        failureThreshold: 8 # Normally probe will stop after 3 attemps. this can increase number of atempts
        