apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-deployment
  labels:
    app: mysql

spec:
  serviceName: mysql-h
  template:
    # Pod definition
    metadata:
      name: myapp-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-volume

  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes:
          - ReadWriteMany # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
        storageClassName: google-storage
        resources:
          requests:
            storage: 50Mi