apiVersion: v1
kind: Pod
metadata:
  name: elephant
spec:
  containers:
    - name: elephant
      image: polinux/stress
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"