apiVersion: v1
kind: Pod
metadata:
  name: elephant
spec:
  containers:
    - name: elephant
      image: polinux/stress
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: size
              operator: In # In | NotIn | Exists (Check documentation)
              values:
                - Large
      # preferredDuringSchedulingIgnoredDuringExecution:
      #   - preference:
            
      #     weight: 
      # Planned(Not Available yet)--> requiredDuringSchedulingRequiredDuringExecution