apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: blue

spec:
  template:
    # Pod definition
    metadata:
      name: blue
      labels:
        name: blue
        
    spec:
      containers:
        - name: blue
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: color
                  operator: In # In | NotIn | Exists (Check documentation)
                  values:
                    - blue
  replicas: 6
  selector:
    matchLabels:
      name: blue