apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  resources:
    requests:
      storage: 1Gi
