apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
spec:
  securityContext:
          runAsUser: 1010
  containers:
    - name: ubuntu-sleeper
      image: ubuntu
      command: ["sleep","10000"]
      securityContext:
          runAsUser: 0
          capabilities:
            add: ["SYS_TIME"]
            