apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mycluster-pgbr-repo
  namespace: pgo
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  resources:
    requests:
      storage: 1Gi
