apiVersion: v1
kind: PersistentVolume
metadata:
  name:  wordpress-persistent-storage
spec:
  accessModes:
    - ReadWriteMany # ReadOnlyMany | ReadWriteOnce | ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/nfs_share/html
    server: 192.168.111.136