apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql

spec:
  template:
    # Pod definition
    metadata:
      name: mysql
      labels:
        name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistant-storage
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
      volumes:
        - name: mysql-persistant-storage
          persistentVolumeClaim:
            claimName: mysql-persistant-storage
  replicas: 2
  selector:
    matchLabels:
      name: mysql
  