apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    name: wordpress

spec:
  template:
    # Pod definition
    metadata:
      name: wordpress
      labels:
        name: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress-persistant-storage
          env:
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
      volumes:
        - name: wordpress-persistant-storage
          persistentVolumeClaim:
            claimName: wordpress-persistant-storage
  replicas: 2
  selector:
    matchLabels:
      type: wordpress
  