apiVersion: v1
kind: DeploymentConfig
metadata:
  name: "simple-webapp-docker"
spec:
  template:
    metadata:
      labels:
        name: "simple-webapp-docker"
    spec:
      containers:
        - name: "simple-webapp-docker"
          image: "simple-webapp-docker:latest"
          ports:
            - containerPort: 8080
              protocol: "TCP"
  replicas: 1
  selector:
    name: "simple-webapp-docker"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - simple-webapp-docker
        from:
          kind: ImageStreamTag
          name: "simple-webapp-docker:latest"
  strategy:
    type: Rolling