apiVersion: v1
kind: Service
metadata:
  name: db # This is the name mentioned inside application
  labels:
    name: db-service
    app: demo-voting-app
spec:
  # type: ClusterIP This is the default type
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-app-pod
    app: demo-voting-app