apiVersion: v1
kind: Service
metadata:
  name: redis # This is the name mentioned inside application
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  # type: ClusterIP This is the default type
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app