apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer # LoadBalancer type works only on public cloud platforms like aws,google cloud
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-pod
    app: demo-voting-app